# Generated by Django 4.2.7 on 2026-05-09 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_interview_prep_skill_gap"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="jobapplication",
            new_name="tracker_job_user_id_01e26e_idx",
            old_name="tracker_job_user_id_updated_idx",
        ),
        migrations.RenameIndex(
            model_name="jobapplication",
            new_name="tracker_job_user_id_890174_idx",
            old_name="tracker_job_user_id_status_idx",
        ),
    ]
