# Generated by Django 4.2.7 on 2026-02-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['resume', 'order'], name='resumes_edu_resume__962eda_idx'),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['resume', '-end_year'], name='resumes_edu_resume__c923af_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['resume', 'order'], name='resumes_exp_resume__157068_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['resume', '-start_date'], name='resumes_exp_resume__9de6dd_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['resume', 'order'], name='resumes_pro_resume__14cf52_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['resume', 'category'], name='resumes_ski_resume__71aaca_idx'),
        ),
    ]
