# Generated by Django 4.2.7 on 2026-02-14 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modification_type', models.CharField(choices=[('manual', 'Manual Edit'), ('optimized', 'AI Optimized'), ('restored', 'Restored from History')], default='manual', max_length=20)),
                ('ats_score', models.FloatField(blank=True, null=True)),
                ('snapshot_data', models.JSONField()),
                ('user_notes', models.TextField(blank=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='resumes.resume')),
            ],
            options={
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['resume', '-created_at'], name='resumes_res_resume__743f75_idx')],
                'unique_together': {('resume', 'version_number')},
            },
        ),
    ]
