# Generated by Django 4.2.7 on 2026-02-14 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_add_uploaded_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField()),
                ('analysis_timestamp', models.DateTimeField(auto_now_add=True)),
                ('keyword_match_score', models.FloatField()),
                ('skill_relevance_score', models.FloatField()),
                ('section_completeness_score', models.FloatField()),
                ('experience_impact_score', models.FloatField()),
                ('quantification_score', models.FloatField()),
                ('action_verb_score', models.FloatField()),
                ('final_score', models.FloatField()),
                ('matched_keywords', models.JSONField(default=list)),
                ('missing_keywords', models.JSONField(default=list)),
                ('weak_action_verbs', models.JSONField(default=list)),
                ('missing_quantifications', models.JSONField(default=list)),
                ('suggestions', models.JSONField(default=list)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='resumes.resume')),
            ],
            options={
                'verbose_name_plural': 'Resume analyses',
                'ordering': ['-analysis_timestamp'],
                'indexes': [models.Index(fields=['resume', '-analysis_timestamp'], name='resumes_res_resume__5b3a34_idx')],
            },
        ),
    ]
