# Generated by Django 4.2.7 on 2026-02-14 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_add_resume_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField()),
                ('optimization_timestamp', models.DateTimeField(auto_now_add=True)),
                ('original_score', models.FloatField()),
                ('optimized_score', models.FloatField(blank=True, null=True)),
                ('improvement_delta', models.FloatField(blank=True, null=True)),
                ('changes_summary', models.JSONField(default=dict)),
                ('detailed_changes', models.JSONField(default=list)),
                ('accepted_changes', models.JSONField(default=list)),
                ('rejected_changes', models.JSONField(default=list)),
                ('user_notes', models.TextField(blank=True)),
                ('optimized_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optimizations_as_optimized', to='resumes.resumeversion')),
                ('original_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optimizations_as_original', to='resumes.resumeversion')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimizations', to='resumes.resume')),
            ],
            options={
                'verbose_name_plural': 'Optimization histories',
                'ordering': ['-optimization_timestamp'],
                'indexes': [models.Index(fields=['resume', '-optimization_timestamp'], name='resumes_opt_resume__9cc312_idx')],
            },
        ),
    ]
