# Generated by Django 4.2.7 on 2026-02-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_add_optimization_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='current_version_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='resume',
            name='last_analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='last_optimized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
