# Generated by Django 4.2.7 on 2026-02-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0007_add_resume_tracking_fields'),
    ]

    operations = [
        # Add composite index for Resume queries by user and analysis timestamp
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['user', '-last_analyzed_at'], name='resumes_res_user_id_last_an_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['user', '-last_optimized_at'], name='resumes_res_user_id_last_op_idx'),
        ),
        
        # Add composite index for ResumeVersion queries
        migrations.AddIndex(
            model_name='resumeversion',
            index=models.Index(fields=['resume', '-version_number'], name='resumes_res_resume__version_idx'),
        ),
        
        # Add index for UploadedResume status queries
        migrations.AddIndex(
            model_name='uploadedresume',
            index=models.Index(fields=['user', 'status'], name='resumes_upl_user_id_status_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedresume',
            index=models.Index(fields=['status', '-uploaded_at'], name='resumes_upl_status_uploaded_idx'),
        ),
        
        # Add composite index for ResumeAnalysis queries by user
        migrations.AddIndex(
            model_name='resumeanalysis',
            index=models.Index(fields=['resume', 'final_score'], name='resumes_res_resume__final_s_idx'),
        ),
        
        # Add composite index for OptimizationHistory queries
        migrations.AddIndex(
            model_name='optimizationhistory',
            index=models.Index(fields=['resume', 'improvement_delta'], name='resumes_opt_resume__improve_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizationhistory',
            index=models.Index(fields=['original_version', 'optimized_version'], name='resumes_opt_origina_optimiz_idx'),
        ),
    ]
