# Generated by Django 4.2.7 on 2026-02-15 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0008_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='optimizationhistory',
            name='resumes_opt_resume__improve_idx',
        ),
        migrations.RemoveIndex(
            model_name='optimizationhistory',
            name='resumes_opt_origina_optimiz_idx',
        ),
        migrations.RemoveIndex(
            model_name='resume',
            name='resumes_res_user_id_last_an_idx',
        ),
        migrations.RemoveIndex(
            model_name='resume',
            name='resumes_res_user_id_last_op_idx',
        ),
        migrations.RemoveIndex(
            model_name='resumeanalysis',
            name='resumes_res_resume__final_s_idx',
        ),
        migrations.RemoveIndex(
            model_name='resumeversion',
            name='resumes_res_resume__version_idx',
        ),
        migrations.RemoveIndex(
            model_name='uploadedresume',
            name='resumes_upl_user_id_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='uploadedresume',
            name='resumes_upl_status_uploaded_idx',
        ),
    ]
