# Generated by Django 4.2.7 on 2026-02-19 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0009_remove_optimizationhistory_resumes_opt_resume__improve_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='github',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='linkedin',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
