# Generated by Django 4.2.7 on 2026-02-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0010_make_optional_fields_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='field',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
