# Generated by Django 4.2.7 on 2026-02-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0011_alter_education_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
