# Generated by Django 4.2.7 on 2026-02-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0012_alter_experience_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='field',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
