# Generated by Django 4.2.7 on 2026-03-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0013_alter_education_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='color_scheme',
            field=models.CharField(default='professional_blue', help_text='Color scheme for resume template', max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='font_family',
            field=models.CharField(default='Arial', help_text='Font family for resume text', max_length=50),
        ),
    ]
