# Generated by Django 4.2.7 on 2026-03-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0014_resume_color_scheme_resume_font_family'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='resumeversion',
            index=models.Index(fields=['resume', 'created_at'], name='resumes_res_resume__e80e38_idx'),
        ),
    ]
