# Generated by Django 4.2.7 on 2026-03-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0015_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_draft',
            field=models.BooleanField(default=True, help_text='Whether resume is in draft state'),
        ),
        migrations.AddField(
            model_name='resume',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='Professional summary'),
        ),
    ]
