# Generated by Django 4.2.7 on 2026-03-07 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0016_add_summary_and_is_draft_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GPA out of 4.0', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='honors',
            field=models.CharField(blank=True, default='', help_text='Honors, awards, or distinctions', max_length=500),
        ),
        migrations.AddField(
            model_name='education',
            name='relevant_coursework',
            field=models.TextField(blank=True, default='', help_text='Relevant courses (comma-separated)'),
        ),
        migrations.AddField(
            model_name='experience',
            name='achievements',
            field=models.TextField(blank=True, default='', help_text='Bullet points of achievements with metrics (one per line)'),
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, default='', help_text='City, State/Country', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='impact',
            field=models.TextField(blank=True, default='', help_text='Quantifiable impact or results achieved'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='proficiency_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='years_of_experience',
            field=models.IntegerField(blank=True, help_text='Years of experience with this skill', null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Brief overview of role'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Brief description of the project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, default='', help_text='Technologies used (comma-separated)', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, help_text='GitHub, live demo, or portfolio link', validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(help_text='e.g., Languages, Frameworks, Tools, Soft Skills', max_length=50),
        ),
    ]
