# Generated by Django 4.2.7 on 2026-05-05 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resumes", "0019_add_certification"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeABTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='e.g. "Software Engineer @ Google — Q1 2025"',
                        max_length=200,
                    ),
                ),
                ("target_role", models.CharField(max_length=200)),
                ("target_company", models.CharField(blank=True, max_length=200)),
                ("job_description", models.TextField(blank=True)),
                (
                    "hypothesis",
                    models.TextField(
                        blank=True,
                        help_text="What you changed and why you think it will perform better",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("concluded", "Concluded"),
                            ("paused", "Paused"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("concluded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "winner",
                    models.CharField(
                        blank=True, choices=[("A", "A"), ("B", "B")], max_length=1
                    ),
                ),
                ("conclusion_notes", models.TextField(blank=True)),
                (
                    "resume_a",
                    models.ForeignKey(
                        help_text="Version A (control)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ab_tests_as_a",
                        to="resumes.resume",
                    ),
                ),
                (
                    "resume_b",
                    models.ForeignKey(
                        help_text="Version B (variant)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ab_tests_as_b",
                        to="resumes.resume",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ab_tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Resume A/B Test",
                "ordering": ["-created_at"],
            },
        ),
    ]
