# Generated by Django 4.2.7 on 2026-02-14 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0006_add_optimization_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('template_file', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='template_thumbnails/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('supports_color_customization', models.BooleanField(default=True)),
                ('supports_font_customization', models.BooleanField(default=True)),
                ('available_colors', models.JSONField(default=list)),
                ('available_fonts', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_scheme', models.CharField(blank=True, max_length=50)),
                ('font_family', models.CharField(blank=True, max_length=100)),
                ('custom_css', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template_customization', to='resumes.resume')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='templates_mgmt.resumetemplate')),
            ],
            options={
                'verbose_name_plural': 'Template customizations',
            },
        ),
    ]
