# Generated by Django 4.2.7 on 2026-02-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_mgmt', '0001_add_template_models'),
    ]

    operations = [
        # Add index for ResumeTemplate queries
        migrations.AddIndex(
            model_name='resumetemplate',
            index=models.Index(fields=['is_active', '-usage_count'], name='templates_m_is_acti_usage_c_idx'),
        ),
        migrations.AddIndex(
            model_name='resumetemplate',
            index=models.Index(fields=['-created_at'], name='templates_m_created_idx'),
        ),
        
        # Add index for TemplateCustomization queries
        migrations.AddIndex(
            model_name='templatecustomization',
            index=models.Index(fields=['template', '-created_at'], name='templates_m_templat_created_idx'),
        ),
    ]
