# Generated by Django 4.2.7 on 2026-02-15 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates_mgmt', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='resumetemplate',
            name='templates_m_is_acti_usage_c_idx',
        ),
        migrations.RemoveIndex(
            model_name='resumetemplate',
            name='templates_m_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='templatecustomization',
            name='templates_m_templat_created_idx',
        ),
    ]
