# Generated by Django 5.0.6 on 2024-09-07 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resume_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='full_name',
            new_name='First_Name',
        ),
    ]
