# Generated by Django 5.0.6 on 2024-09-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_rename_full_name_resume_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='Last_Name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='First_Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
