# Generated by Django 5.0.6 on 2024-09-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_resume_last_name_alter_resume_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='Last_Name',
        ),
        migrations.AlterField(
            model_name='resume',
            name='First_Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
