# Generated by Django 4.2.7 on 2026-05-05 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Email Verification Token",
            },
        ),
        migrations.RenameIndex(
            model_name="activitylog",
            new_name="authenticat_user_id_e91320_idx",
            old_name="auth_actlog_user_idx",
        ),
        migrations.RenameIndex(
            model_name="savedjobdescription",
            new_name="authenticat_user_id_10a2be_idx",
            old_name="auth_savedjd_user_idx",
        ),
        migrations.AlterField(
            model_name="savedjobdescription",
            name="title",
            field=models.CharField(
                help_text='e.g. "Senior Python Dev @ Google"', max_length=200
            ),
        ),
        migrations.AddField(
            model_name="emailverificationtoken",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_verification",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
